package network;

public enum MessageType
{
    CHAT_MESSAGE,
    CHAT_REPOSITORY,
    SET_ID,
    SET_CLIENT_INFO,
    PLAYERS_LIST,
    GET_MAP,
    RET_MAP,
    ERROR,
    ATTACK_REPORTS_LIST,
    ATTACK_REPORT,
    ATTACK_STARTED,
    ATTACK_REQUEST,
    ATTACK_UDP_READY
}
